#pre-set arguments for testing TMT-pipeline script
workdir <- ""
#datafile <- "proteinGroups.txt"
#datafile <- "Phospho (STY)Sites.txt"
datafile <- "PD3.1-file-name.xlsx"
metadatafile <- "sampledata.txt"
exp <- ""
REGEX <- "no"
SLN <- "Yes"
#SLN <- "no"
PTM <- "none"
#PTM <- "P"
DE <- "Yes"
stat <- "q"
qval <- 0.1
compsfile <- "comps.xlsx"
annot <- "None"